### ISSUE TITLE
Is it possible to install via pip?

### ISSUE THREAD

**Issue by bakroistvan** [xtacocorex/CHIP_IO#13]
Is it possible to install via pip?

**Comment by xtacocorex** [comment]
Try this: https://pypi.python.org/pypi/CHIP-IO
Let me know how it goes, this is the first time I've done this.

**Comment by xtacocorex** [comment]
sudo pip install CHIP-IO 

Still need the dependencies outlined in the README.  It will complain about overlay stuff, disregard that at the moment as that's a future currently in pull request.

**Comment by xtacocorex** [comment]
Confirmed that this installs just fine on the CHIP.  Just make sure the proper libs are installed on the CHIP before pulling down. Closing this. :)  Thanks for the feature request!
