### ISSUE TITLE
Handle CHIP Pro

### ISSUE THREAD

**Issue by xtacocorex** [xtacocorex/CHIP_IO#32]
The NTC CHIP Pro is a smaller CHIP with the GR8 SOC that is designed for embedded applications.

The IO of the CHIP Pro is slightly different from the CHIP.

Need to come up with an elegant way to handle IO on the CHIP Pro while maintaining compatibility with the CHIP/PocketCHIP.

**Comment by Flexshot** [comment]
Would love to discuss how this should be implemented. I have a method in mind and most likely so do you. Feel free to message me in the forums. I can implement this in a few days.

**Comment by xtacocorex** [comment]
I really didn't have a method in mind just yet, was moreso going to try it on the CHIP Pro (something you're already doing) and see where things failed miserably.  

I was going to add another field to the pins_t struct that denotes CHIP/CHIP Pro support.  The XIOs and most of the LCD pins are definitely not on the CHIP Pro, but I haven't dove into and really researched everything yet.

**Comment by xtacocorex** [comment]
Add per PWM channel cleanup since there are 2 PWM channels on the CHIP Pro.  This would help chip-python-aREST...

**Comment by xtacocorex** [comment]
Forgot to add the issue tag to this commit: https://github.com/xtacocorex/CHIP_IO/commit/c5dbede3c4cd37552f37af7f5396fd1c5af72a87
