### ISSUE TITLE
Prevent file opening whenever GPIO value is set

### ISSUE THREAD

**Issue by laurivosandi** [xtacocorex/CHIP_IO#34]
Currently it seems file is opened whenever GPIO value is set (eg from soft PWM). I think it would make more sense to open the file handle when pin is exported and close the file handle when pin is unexported.

https://github.com/xtacocorex/CHIP_IO/blob/master/source/event_gpio.c#L385

**Comment by xtacocorex** [comment]
So, the Hardware PWM code has this feature and I am beginning to wonder if it's the reason why the code isn't working properly.  I'm still investigating all the things at the moment, but I'll keep this under consideration.

**Comment by laurivosandi** [comment]
With current sysfs approach it's not going to get much better but opening/closing file handle every PWM cycle seems rather silly :)

**Comment by xtacocorex** [comment]
This was actually a whole lot easier than I was thinking.  My thought process was over complicating things.

**Comment by laurivosandi** [comment]
Nice job, going to give a try tomorrow :)
