### ISSUE TITLE
Add way to easily and quickly toggle pin direction

### ISSUE THREAD

**Issue by xtacocorex** [xtacocorex/CHIP_IO#36]
Per discussion here: https://bbs.nextthing.co/t/change-gpio-direction/13162

**Comment by blueSolder** [comment]
I have gone over the source code and think that direction changing can be implemented by copying  py_setup_channel in py_gpio.c rename copy, edit out not required lines and add a new entry to gpio_methods[].
Not sure what to do next though, am new to github.

**Comment by xtacocorex** [comment]
Yeah, it shouldn't be too hard to implement this feature. Just need to get past the next 2 days and I'll have some free time to work on CHIP_IO.

**Comment by blueSolder** [comment]
Have done above and got it working.

**Comment by aninternetof** [comment]
That's great! If you'd like to make a pull request, that would be one way to let us try out and adopt your change.

**Comment by xtacocorex** [comment]
I second what @aninternetof said @blueSolder.  If you forked the code, you can definitely contribute and submit a pull request. Otherwise, I plan on getting to that this week.

**Comment by xtacocorex** [comment]
Closed per PR#39 being merged.
