### ISSUE TITLE
Allow SoftPWM to act as a Servo

### ISSUE THREAD

**Issue by xtacocorex** [xtacocorex/CHIP_IO#41]
Add the ability to set the SoftPWM to mimic an RC Servo so we can specify an angle and force the servo to that position.  Would need the following:

1. SoftPWM Type: Normal, Servo
2. Set Servo Angle Range
3. Set Servo Position

Refer to: https://en.wikipedia.org/wiki/Servo_control

**Comment by Flexshot** [comment]
I think the Servo class should be separate from hardware and software pwm code.
