### ISSUE TITLE
Additional error handling and checking in pwm_start

### ISSUE THREAD

**Issue by Flexshot** [xtacocorex/CHIP_IO#53]
Currently we do nothing with rtnval in pwm_start except reset it to 0. We should check to see if we got the expected result.

https://github.com/xtacocorex/CHIP_IO/blob/master/source/c_pwm.c#L395

**Comment by xtacocorex** [comment]
It's like you're finding where I completely forgot what I was doing.  The whole plan of the rtnval was to check the enable so it didn't do anything else if it failed.  In the excitement of getting stuff to work over Christmas, I missed that. Good find!
