### ISSUE TITLE
Abstract out the DEBUG functionality in c_pwm.c

### ISSUE THREAD

**Issue by Flexshot** [xtacocorex/CHIP_IO#55]
Let's abstract out the DEBUG functionality so that we can reuse functions in other classes besides PWM and potentially add logging.

**Comment by xtacocorex** [comment]
Totally great idea! Adding debug to each "module" was something I had in the back of my mind to do since it was super handy to have the output while trying to get the PWM fixed.

The abstraction idea is good though, because then it's enabled for the entirety of the library.
