### ISSUE TITLE
CHIP_IO low-level library for using in other scripting languages

### ISSUE THREAD

**Issue by mikolajzieba** [xtacocorex/CHIP_IO#67]
Hi,

Is there any simple possibility to use easily your library in other languages? What I want to do is to receive interrupts on GPIO states change in a PHP script, but I don't want to do this through python scripts to save on resources and time. 
I can see in your code that all the low-level operations are coded in C, so is there an option or actually existing library with that code, which allows to execute all these operations using compiled binaries?

**Comment by xtacocorex** [comment]
@groguard has started work porting this code to a pure C implementation, check out: https://github.com/Groguard/CHIP_IO_C.

Going to close this issue.
