### ISSUE TITLE
bounce time

### ISSUE THREAD

**Issue by C0deGyver** [xtacocorex/CHIP_IO#71]
As far as I can tell bounce time for edge detection has yer to be implemented. At least it is not in the manual. This would be a nice addition.

**Comment by xtacocorex** [comment]
bouncetime is an optional argument for the edge detection code.  It is able to be set.  That was code that was part of the library when I ported over from the BeagleBoneBlack.

As an example:
`static int add_py_callback(char *channel, int gpio, int edge, unsigned int bouncetime, PyObject *cb_func)`

I will use this to update the README though.
