### ISSUE TITLE
Could not open GPIO 1015 value file

### ISSUE THREAD

**Issue by nickcdavis** [xtacocorex/CHIP_IO#72]
Hi all,

I'm running into the following issue when attempting to write to a channel using Pocket Chip:

> RuntimeError: Could no write 0 on channel GPIO1. (open_value_file: could not open '/sys/class/gpio/gpio1015/value' (No such file or directory)
> gpio_get_value: could not open GPIO 1015 value file)

When I look at the /sys/class/gpio/ directory, it does contain other gpio directories, except with different numbers.

I did use the Manual installation for python 2.7. However, I also had to reinstall CHIP_IO a couple times, do to ntpdate issues prior to installation.

FWIW, here's the code for the file I'm trying to 

import CHIP_IO.GPIO as GPIO
import time
GPIO.cleanup()
GPIO.setup("GPIO1", GPIO.OUT)
print "Toggling GPIO1 10 times..."
for i in range(0,10):
        GPIO.output("GPIO1", GPIO.LOW)
        time.sleep(0.1)
        GPIO.output("GPIO1", GPIO.HIGH)
        time.sleep(0.1)
        GPIO.cleanup()

Hope this helps, thanks!

**Comment by xtacocorex** [comment]
Nick, sorry for not responding sooner. Glad you figured out the issue!
