### ISSUE TITLE
binary wheel pypi package?

### ISSUE THREAD

**Issue by pztrick** [xtacocorex/CHIP_IO#77]
Hi,
I think it could be useful to upload `armhf` binary package to PyPi to avoid native compilation? I do see the `.deb` package in Releases but this could make it more useful for other non-Debian Linux flavors on GR8 and also allow tagging dependencies in `requirements.txt`.

For my part, I am using Python 3.6 so needed to native compile natively anyway. :) But am compiling on other ARM machine to save GR8 disk space. :)

---

setup.cfg:

```
[bdist_wheel]
universal = 1

[metadata]
license_file = LICENSE
```

```
python setup.py sdist bdist_wheel upload
```

**Comment by xtacocorex** [comment]
This is a good idea and is something I haven't gotten around to doing.  I'll try to get to this soon.

**Comment by xtacocorex** [comment]
Just implemented this and have unstested wheel files pushed to pypi for Python 2.7 and 3.4. Thanks for the help in this!
